"use client";

import { formatTimeMinutes } from "../utils/transcript-utils";

interface SummaryPanelProps {
	data: {
		duration?: number;
		aiSummary?: {
			overview?: string;
			topics?: { title: string; body: string }[];
			nextSteps?: string[];
			chapters?: { startSec: number; title: string; body: string }[];
		};
		speakerCount?: number;
	};
	onVideoJump?: (seconds: number) => void;
}

export function SummaryPanel({ data, onVideoJump }: SummaryPanelProps) {
	const { aiSummary } = data;
	const topics = aiSummary?.topics ?? [];
	const nextSteps = aiSummary?.nextSteps ?? [];
	const chapters = aiSummary?.chapters ?? [];

	if (!aiSummary) {
		return (
			<div className="rounded-xl border border-gray-200 bg-gray-50 px-4 py-6 text-center">
				<p className="text-sm text-gray-500">No AI summary available.</p>
			</div>
		);
	}

	return (
		<div className="flex flex-col gap-5">
			{/* Header */}
			<div className="flex items-center gap-2">
				<h2 className="text-base font-semibold text-gray-900">Summary</h2>
				<span className="rounded-full bg-blue-50 border border-blue-100 px-2 py-0.5 text-xs font-medium text-blue-700">
					Generated by AI
				</span>
			</div>

			{/* Overview */}
			{aiSummary.overview && (
				<div className="rounded-xl border border-blue-100 bg-blue-50 px-4 py-3">
					<p className="text-sm leading-relaxed text-gray-800">
						{aiSummary.overview}
					</p>
				</div>
			)}

			{/* Chapters */}
			{chapters.length > 0 && (
				<div>
					<h3 className="mb-2 text-sm font-semibold text-gray-700">Chapters</h3>
					<div className="flex flex-col gap-2">
						{chapters.map((chapter) => (
							<div
								key={chapter.startSec}
								className="flex items-start gap-3 rounded-xl border border-gray-200 bg-white p-3"
							>
								<button
									type="button"
									onClick={() => onVideoJump?.(chapter.startSec)}
									className="mt-0.5 shrink-0 rounded-md bg-gray-100 px-2 py-0.5 text-xs font-mono font-medium text-gray-700 transition-colors hover:bg-blue-100 hover:text-blue-700"
								>
									{formatTimeMinutes(chapter.startSec)}
								</button>
								<div className="min-w-0">
									<p className="text-sm font-medium text-gray-900">
										{chapter.title}
									</p>
									{chapter.body && (
										<p className="mt-0.5 text-xs leading-relaxed text-gray-600">
											{chapter.body}
										</p>
									)}
								</div>
							</div>
						))}
					</div>
				</div>
			)}

			{/* Topics */}
			{topics.length > 0 && (
				<div>
					<h3 className="mb-2 text-sm font-semibold text-gray-700">Topics</h3>
					<div className="grid grid-cols-1 gap-2 sm:grid-cols-2">
						{topics.map((topic) => (
							<div
								key={topic.title}
								className="rounded-xl border border-gray-200 bg-white p-3"
							>
								<p className="mb-1 text-sm font-medium text-gray-900">
									{topic.title}
								</p>
								<p className="text-xs leading-relaxed text-gray-600">
									{topic.body}
								</p>
							</div>
						))}
					</div>
				</div>
			)}

			{/* Next Steps */}
			{nextSteps.length > 0 && (
				<div>
					<h3 className="mb-2 text-sm font-semibold text-gray-700">
						Next Steps
					</h3>
					<ol className="flex flex-col gap-2">
						{nextSteps.map((step, i) => (
							<li key={i} className="flex items-start gap-2">
								<span className="mt-0.5 flex size-5 shrink-0 items-center justify-center rounded-full bg-blue-50 border border-blue-100 text-xs font-semibold text-blue-700">
									{i + 1}
								</span>
								<span className="text-sm text-gray-800">{step}</span>
							</li>
						))}
					</ol>
				</div>
			)}

			{/* Empty state when all sections are empty */}
			{topics.length === 0 && nextSteps.length === 0 && chapters.length === 0 && !aiSummary.overview && (
				<p className="text-sm text-gray-500">No content available yet.</p>
			)}
		</div>
	);
}
